function injectDanteLayout() {

  // Insert layout shell if not present
  let layoutShell = document.getElementById('layout-shell');

  if (!layoutShell) {
    layoutShell = document.createElement('div');
    layoutShell.id = 'layout-shell';
    document.body.insertBefore(layoutShell, document.body.firstChild);
  }

  if (typeof window.sharedNavMarkup === 'string') {
    layoutShell.innerHTML = window.sharedNavMarkup;

    const storedUser = localStorage.getItem('user');
const currentUser = storedUser ? JSON.parse(storedUser) : null;

if (currentUser?.role !== 'admin') {
    // Hide Reports navigation
    layoutShell.querySelector('#reports-nav-link')?.remove();
    layoutShell.querySelector('#reports-side-nav-link')?.remove();

    // Hide any Reports link generated by another page layout
    [...layoutShell.querySelectorAll('a')].forEach(link => {
        if (link.textContent.trim() === 'Reports' ||
            link.getAttribute('href') === 'reports.html' ||
            link.getAttribute('href') === '/legacy/pages/reports.html') {
            link.remove();
        }
    });
}

    // Hide admin-only navigation for staff

    if (currentUser?.role !== 'admin') {
      layoutShell.querySelector('#reports-nav-link')?.remove();
      layoutShell.querySelector('#reports-side-nav-link')?.remove();
    }
  }
}

if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', injectDanteLayout);
} else {
  injectDanteLayout();
}
