-- PROPOSAL ONLY: do not execute until live PostgreSQL types, constraints,
-- and existing RPC definitions have been reviewed and approved.
--
-- This migration preserves create_transfer, receive_transfer,
-- delivery_transactions, and all existing transfer records.
--
-- Verified live assumptions:
--   branches.id, products.uuid, product_uuid, and branch_id use UUID values.
--   serialized_units exposes id, product_uuid, branch_id, sequence_number,
--   unit_barcode, status, and updated_at.
--   transfer_headers and transfer_items are not present in the live schema.
--
-- MUST VERIFY BEFORE DEPLOYMENT:
--   1. serialized_units.id is UUID.
--   2. products.uuid and branches.id are valid FK targets.
--   3. serialized_units.status accepts AVAILABLE and IN_TRANSIT.
--   4. stock_transactions.tracking_code is nullable and accepts TRANSFER_OUT/
--      TRANSFER_IN (these values are present in live data).
--   5. gen_random_uuid() is available.
--   6. inventory has a verified uniqueness or locking contract for
--      (product_uuid, branch_id) if a missing-row race is to be fully prevented.
--      If no such key is verified live, the migration leaves the race as a
--      known assumption and documents it below.
--   7. request.jwt.claims and branch_id claim are available in the live auth
--      context used by the backend.
--
-- No serialized_units rows are created by this proposal. Existing AVAILABLE
-- units are reserved and moved only when enough units exist.

CREATE TABLE public.transfer_headers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  tracking_code TEXT NOT NULL UNIQUE,
  source_branch_id UUID NOT NULL REFERENCES public.branches(id) ON DELETE RESTRICT,
  destination_branch_id UUID NOT NULL REFERENCES public.branches(id) ON DELETE RESTRICT,
  status TEXT NOT NULL DEFAULT 'IN_TRANSIT'
    CHECK (status IN ('IN_TRANSIT', 'RECEIVED', 'CANCELLED')),
  created_by TEXT NOT NULL DEFAULT 'system',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT transfer_headers_distinct_branches
    CHECK (source_branch_id <> destination_branch_id)
);

CREATE INDEX idx_transfer_headers_source_date
  ON public.transfer_headers(source_branch_id, created_at DESC);

CREATE INDEX idx_transfer_headers_destination_date
  ON public.transfer_headers(destination_branch_id, created_at DESC);

CREATE TABLE public.transfer_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  transfer_id BIGINT NOT NULL
    REFERENCES public.transfer_headers(id) ON DELETE CASCADE,
  product_uuid UUID NOT NULL REFERENCES public.products(uuid) ON DELETE RESTRICT,
  barcode TEXT NOT NULL,
  quantity INTEGER NOT NULL CHECK (quantity > 0 AND quantity <= 1000),
  item_order INTEGER NOT NULL CHECK (item_order > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT transfer_items_order_unique
    UNIQUE (transfer_id, item_order),
  CONSTRAINT transfer_items_product_unique
    UNIQUE (transfer_id, product_uuid)
);

CREATE INDEX idx_transfer_items_transfer_order
  ON public.transfer_items(transfer_id, item_order);

CREATE INDEX idx_transfer_items_product
  ON public.transfer_items(product_uuid);

CREATE TABLE public.transfer_item_units (
  transfer_item_id BIGINT NOT NULL
    REFERENCES public.transfer_items(id) ON DELETE CASCADE,
  serialized_unit_id UUID NOT NULL
    REFERENCES public.serialized_units(id) ON DELETE RESTRICT,
  unit_order INTEGER NOT NULL CHECK (unit_order > 0),
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  PRIMARY KEY (transfer_item_id, serialized_unit_id),
  CONSTRAINT transfer_item_units_order_unique
    UNIQUE (transfer_item_id, unit_order)
);

-- A serialized unit may appear in multiple historical transfers over its
-- lifetime, but only one active transfer may reserve the same unit at a time.
-- The active marker keeps this invariant local to the table so the partial
-- unique index does not require an illegal cross-table subquery.
CREATE UNIQUE INDEX idx_transfer_item_units_active_unit
  ON public.transfer_item_units(serialized_unit_id)
  WHERE is_active;

CREATE INDEX idx_transfer_item_units_unit
  ON public.transfer_item_units(serialized_unit_id);

CREATE INDEX idx_transfer_item_units_item_order
  ON public.transfer_item_units(transfer_item_id, unit_order);

CREATE OR REPLACE FUNCTION public.create_multi_product_transfer(
  p_source_branch_id UUID,
  p_destination_branch_id UUID,
  p_items JSONB,
  p_created_by TEXT DEFAULT 'system'
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_transfer_id BIGINT;
  v_tracking_code TEXT;
  v_item JSONB;
  v_item_order INTEGER;
  v_product_uuid UUID;
  v_quantity INTEGER;
  v_barcode TEXT;
  v_product_barcode TEXT;
  v_product_name TEXT;
  v_unit TEXT;
  v_inventory_quantity INTEGER;
  v_item_id BIGINT;
  v_unit_id UUID;
  v_unit_order INTEGER;
  v_units JSONB;
  v_result_items JSONB := '[]'::JSONB;
  v_source_branch_name TEXT;
  v_destination_branch_name TEXT;
  v_item_count INTEGER;
  v_distinct_product_count INTEGER;
  v_candidate_count INTEGER;
  v_update_rows INTEGER;
BEGIN
  IF p_source_branch_id IS NULL OR p_destination_branch_id IS NULL THEN
    RAISE EXCEPTION 'source_and_destination_required';
  END IF;

  IF p_source_branch_id = p_destination_branch_id THEN
    RAISE EXCEPTION 'source_and_destination_must_differ';
  END IF;

  IF p_items IS NULL
     OR jsonb_typeof(p_items) <> 'array'
     OR jsonb_array_length(p_items) = 0 THEN
    RAISE EXCEPTION 'items_required';
  END IF;

  IF jsonb_array_length(p_items) > 50 THEN
    RAISE EXCEPTION 'too_many_items';
  END IF;

  -- This migration does not authenticate callers from request.jwt.claims because
  -- the app verifies a custom JWT in Express (req.user) and does not expose a
  -- branch_id claim or Supabase Auth claim set here.
  -- Authorization must happen in the backend before invoking this RPC. The
  -- backend resolves req.user.role and req.user.branch to the live branch row,
  -- validates the source branch, and only then passes the branch UUIDs to this
  -- function. This RPC validates branch relationships and input integrity, but it
  -- does not attempt to re-derive auth from SQL session state.
  SELECT branch_name INTO v_source_branch_name
  FROM public.branches
  WHERE id = p_source_branch_id;

  IF v_source_branch_name IS NULL THEN
    RAISE EXCEPTION 'source_branch_not_found';
  END IF;

  SELECT branch_name INTO v_destination_branch_name
  FROM public.branches
  WHERE id = p_destination_branch_id;

  IF v_destination_branch_name IS NULL THEN
    RAISE EXCEPTION 'destination_branch_not_found';
  END IF;

  SELECT COUNT(*), COUNT(DISTINCT (value->>'product_uuid'))
  INTO v_item_count, v_distinct_product_count
  FROM jsonb_array_elements(p_items);

  IF v_item_count <> v_distinct_product_count THEN
    RAISE EXCEPTION 'duplicate_products_not_allowed';
  END IF;

  -- Validate and lock every source inventory row in deterministic UUID order.
  -- This prevents deadlock-prone mismatched updates while still preserving the
  -- transfer's product order later in the function.
  FOR v_item IN
    SELECT value
    FROM jsonb_array_elements(p_items)
    ORDER BY (value->>'product_uuid')::UUID
  LOOP
    v_product_uuid := (v_item->>'product_uuid')::UUID;
    v_quantity := (v_item->>'quantity')::INTEGER;

    IF v_quantity IS NULL OR v_quantity <= 0 OR v_quantity > 1000 THEN
      RAISE EXCEPTION 'quantity_must_be_positive_and_reasonable';
    END IF;

    IF NOT EXISTS (
      SELECT 1
      FROM public.products
      WHERE uuid = v_product_uuid
        AND is_active = TRUE
    ) THEN
      RAISE EXCEPTION 'product_not_found_or_inactive';
    END IF;

    SELECT quantity INTO v_inventory_quantity
    FROM public.inventory
    WHERE product_uuid = v_product_uuid
      AND branch_id = p_source_branch_id
    FOR UPDATE;

    IF v_inventory_quantity IS NULL OR v_inventory_quantity < v_quantity THEN
      RAISE EXCEPTION 'insufficient_aggregate_stock';
    END IF;

    SELECT COUNT(*) INTO v_candidate_count
    FROM public.serialized_units
    WHERE product_uuid = v_product_uuid
      AND branch_id = p_source_branch_id
      AND status = 'AVAILABLE';

    IF v_candidate_count < v_quantity THEN
      RAISE EXCEPTION 'insufficient_serialized_units';
    END IF;
  END LOOP;

  v_tracking_code := 'TRF-' || upper(substr(replace(gen_random_uuid()::TEXT, '-', ''), 1, 12));

  INSERT INTO public.transfer_headers (
    tracking_code,
    source_branch_id,
    destination_branch_id,
    status,
    created_by
  )
  VALUES (
    v_tracking_code,
    p_source_branch_id,
    p_destination_branch_id,
    'IN_TRANSIT',
    COALESCE(NULLIF(trim(p_created_by), ''), 'system')
  )
  RETURNING id INTO v_transfer_id;

  -- Submitted array order is the authoritative product order.
  FOR v_item, v_item_order IN
    SELECT value, ordinality::INTEGER
    FROM jsonb_array_elements(p_items) WITH ORDINALITY
  LOOP
    v_product_uuid := (v_item->>'product_uuid')::UUID;
    v_quantity := (v_item->>'quantity')::INTEGER;

    SELECT product_name, barcode, unit
    INTO v_product_name, v_product_barcode, v_unit
    FROM public.products
    WHERE uuid = v_product_uuid
      AND is_active = TRUE;

    INSERT INTO public.transfer_items (
      transfer_id,
      product_uuid,
      barcode,
      quantity,
      item_order
    )
    VALUES (
      v_transfer_id,
      v_product_uuid,
      v_product_barcode,
      v_quantity,
      v_item_order
    )
    RETURNING id INTO v_item_id;

    v_units := '[]'::JSONB;
    v_unit_order := 0;

    -- A deterministic sequence order minimizes deadlocks and preserves the
    -- original serialized-unit sequence when units are reserved.
    FOR v_unit_id IN
      SELECT id
      FROM public.serialized_units
      WHERE product_uuid = v_product_uuid
        AND branch_id = p_source_branch_id
        AND status = 'AVAILABLE'
      ORDER BY sequence_number ASC, id ASC
      LIMIT v_quantity
      FOR UPDATE
    LOOP
      v_unit_order := v_unit_order + 1;

      INSERT INTO public.transfer_item_units (
        transfer_item_id,
        serialized_unit_id,
        unit_order
      )
      VALUES (
        v_item_id,
        v_unit_id,
        v_unit_order
      );

      SELECT unit_barcode INTO v_barcode
      FROM public.serialized_units
      WHERE id = v_unit_id;

      v_units := v_units || jsonb_build_array(v_barcode);
    END LOOP;

    IF v_unit_order <> v_quantity THEN
      RAISE EXCEPTION 'insufficient_serialized_units_for_product';
    END IF;

    UPDATE public.serialized_units
    SET status = 'IN_TRANSIT',
        updated_at = NOW()
    WHERE id IN (
      SELECT serialized_unit_id
      FROM public.transfer_item_units
      WHERE transfer_item_id = v_item_id
    )
      AND status = 'AVAILABLE'
      AND branch_id = p_source_branch_id
      AND product_uuid = v_product_uuid;

    GET DIAGNOSTICS v_update_rows = ROW_COUNT;
    IF v_update_rows <> v_quantity THEN
      RAISE EXCEPTION 'serialized_unit_state_transition_failed';
    END IF;

    UPDATE public.inventory
    SET quantity = quantity - v_quantity,
        last_updated = NOW()
    WHERE product_uuid = v_product_uuid
      AND branch_id = p_source_branch_id;

    INSERT INTO public.stock_transactions (
      product_uuid,
      branch_id,
      barcode,
      branch,
      type,
      quantity,
      user_name,
      date,
      tracking_code
    )
    VALUES (
      v_product_uuid,
      p_source_branch_id,
      v_product_barcode,
      v_source_branch_name,
      'TRANSFER_OUT',
      v_quantity,
      COALESCE(NULLIF(trim(p_created_by), ''), 'system'),
      NOW(),
      v_tracking_code
    );

    v_result_items := v_result_items || jsonb_build_array(
      jsonb_build_object(
        'product_uuid', v_product_uuid,
        'product_name', v_product_name,
        'unit', v_unit,
        'barcode', v_product_barcode,
        'quantity', v_quantity,
        'item_order', v_item_order,
        'unit_barcodes', v_units
      )
    );
  END LOOP;

  RETURN jsonb_build_object(
    'transfer_id', v_transfer_id,
    'tracking_code', v_tracking_code,
    'source_branch_id', p_source_branch_id,
    'source_branch', v_source_branch_name,
    'destination_branch_id', p_destination_branch_id,
    'destination_branch', v_destination_branch_name,
    'status', 'IN_TRANSIT',
    'items', v_result_items
  );
END;
$$;

CREATE OR REPLACE FUNCTION public.receive_multi_product_transfer(
  p_tracking_code TEXT,
  p_received_by TEXT DEFAULT 'system'
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_transfer RECORD;
  v_item RECORD;
  v_unit RECORD;
  v_current_quantity INTEGER;
  v_result_items JSONB := '[]'::JSONB;
  v_units JSONB;
  v_unit_count INTEGER;
  v_update_rows INTEGER;
BEGIN
  IF trim(COALESCE(p_tracking_code, '')) = '' THEN
    RAISE EXCEPTION 'tracking_code_required';
  END IF;

  -- This migration deliberately does not rely on request.jwt.claims or a
  -- branch_id JWT claim. The current application verifies a custom JWT in
  -- Express (req.user.id, req.user.username, req.user.role, req.user.branch) and
  -- resolves the branch information in backend code before calling this RPC.
  -- The SQL layer validates transfer and branch relationships, but it does not
  -- attempt to authenticate the caller from database session state.
  SELECT * INTO v_transfer
  FROM public.transfer_headers
  WHERE tracking_code = trim(p_tracking_code)
  FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'transfer_not_found';
  END IF;

  IF v_transfer.status <> 'IN_TRANSIT' THEN
    RAISE EXCEPTION 'transfer_not_in_transit';
  END IF;

  -- Backend authorization: the caller must have been authenticated in Express,
  -- and the destination branch must already have been resolved from req.user
  -- before invoking this RPC. This function trusts the caller-supplied branch
  -- UUIDs only as already-validated transport values, not as source-of-truth
  -- authentication state.

  -- Lock destination inventory rows in deterministic product UUID order.
  FOR v_item IN
    SELECT ti.*
    FROM public.transfer_items ti
    WHERE ti.transfer_id = v_transfer.id
    ORDER BY ti.product_uuid, ti.item_order
  LOOP
    SELECT COUNT(*) INTO v_unit_count
    FROM public.transfer_item_units tiu
    WHERE tiu.transfer_item_id = v_item.id;

    IF v_unit_count <> v_item.quantity THEN
      RAISE EXCEPTION 'unit_count_mismatch';
    END IF;

    v_units := '[]'::JSONB;
    FOR v_unit IN
      SELECT su.id, su.product_uuid, su.branch_id, su.status, su.unit_barcode
      FROM public.transfer_item_units tiu
      JOIN public.serialized_units su ON su.id = tiu.serialized_unit_id
      WHERE tiu.transfer_item_id = v_item.id
      ORDER BY tiu.unit_order, su.sequence_number, su.id
      FOR UPDATE OF su
    LOOP
      IF v_unit.product_uuid <> v_item.product_uuid THEN
        RAISE EXCEPTION 'serialized_unit_product_mismatch';
      END IF;

      IF v_unit.status <> 'IN_TRANSIT' THEN
        RAISE EXCEPTION 'serialized_unit_not_in_transit';
      END IF;

      IF v_unit.branch_id <> v_transfer.source_branch_id THEN
        RAISE EXCEPTION 'serialized_unit_source_branch_mismatch';
      END IF;

      v_units := v_units || jsonb_build_array(v_unit.unit_barcode);
    END LOOP;

    IF jsonb_array_length(v_units) <> v_item.quantity THEN
      RAISE EXCEPTION 'serialized_unit_count_mismatch';
    END IF;

    SELECT quantity INTO v_current_quantity
    FROM public.inventory
    WHERE product_uuid = v_item.product_uuid
      AND branch_id = v_transfer.destination_branch_id
    FOR UPDATE;

    -- The live schema has not been verified to include a unique constraint on
    -- inventory(product_uuid, branch_id). Without that, a concurrent missing-row
    -- insert can still race. This migration intentionally does not invent a new
    -- schema requirement; the missing-row race must be addressed by the live key
    -- or a verified migration constraint before production use.
    IF v_current_quantity IS NULL THEN
      INSERT INTO public.inventory (
        product_uuid, branch_id, branch, quantity, last_updated
      )
      VALUES (
        v_item.product_uuid,
        v_transfer.destination_branch_id,
        (SELECT branch_name FROM public.branches WHERE id = v_transfer.destination_branch_id),
        v_item.quantity,
        NOW()
      );
    ELSE
      UPDATE public.inventory
      SET quantity = quantity + v_item.quantity,
          last_updated = NOW()
      WHERE product_uuid = v_item.product_uuid
        AND branch_id = v_transfer.destination_branch_id;
    END IF;

    UPDATE public.serialized_units
    SET branch_id = v_transfer.destination_branch_id,
        status = 'AVAILABLE',
        updated_at = NOW()
    WHERE id IN (
      SELECT serialized_unit_id
      FROM public.transfer_item_units
      WHERE transfer_item_id = v_item.id
    )
      AND product_uuid = v_item.product_uuid
      AND branch_id = v_transfer.source_branch_id
      AND status = 'IN_TRANSIT';

    GET DIAGNOSTICS v_update_rows = ROW_COUNT;
    IF v_update_rows <> v_item.quantity THEN
      RAISE EXCEPTION 'serialized_unit_state_transition_failed';
    END IF;

    UPDATE public.transfer_item_units
    SET is_active = FALSE
    WHERE transfer_item_id = v_item.id;

    INSERT INTO public.stock_transactions (
      product_uuid,
      branch_id,
      barcode,
      branch,
      type,
      quantity,
      user_name,
      date,
      tracking_code
    )
    VALUES (
      v_item.product_uuid,
      v_transfer.destination_branch_id,
      v_item.barcode,
      (SELECT branch_name FROM public.branches WHERE id = v_transfer.destination_branch_id),
      'TRANSFER_IN',
      v_item.quantity,
      COALESCE(NULLIF(trim(p_received_by), ''), 'system'),
      NOW(),
      v_transfer.tracking_code
    );

    v_result_items := v_result_items || jsonb_build_array(
      jsonb_build_object(
        'product_uuid', v_item.product_uuid,
        'barcode', v_item.barcode,
        'quantity', v_item.quantity,
        'item_order', v_item.item_order,
        'unit_barcodes', v_units
      )
    );
  END LOOP;

  UPDATE public.transfer_headers
  SET status = 'RECEIVED',
      updated_at = NOW()
  WHERE id = v_transfer.id
    AND status = 'IN_TRANSIT';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'transfer_state_transition_failed';
  END IF;

  RETURN jsonb_build_object(
    'transfer_id', v_transfer.id,
    'tracking_code', v_transfer.tracking_code,
    'source_branch_id', v_transfer.source_branch_id,
    'destination_branch_id', v_transfer.destination_branch_id,
    'status', 'RECEIVED',
    'items', v_result_items
  );
END;
$$;

REVOKE EXECUTE ON FUNCTION public.create_multi_product_transfer(UUID, UUID, JSONB, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.create_multi_product_transfer(UUID, UUID, JSONB, TEXT) TO service_role;
REVOKE EXECUTE ON FUNCTION public.receive_multi_product_transfer(TEXT, TEXT) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.receive_multi_product_transfer(TEXT, TEXT) TO service_role;

-- SECURITY NOTE:
-- This migration does not alter or replace existing single-product transfer
-- functions. The new RPCs are SECURITY DEFINER, but they are not intended to be
-- public or unauthenticated entry points. The actual application authenticates
-- with a custom Node/Express JWT (req.user.id, req.user.username, req.user.role,
-- req.user.branch), and the backend must resolve branch identity from that
-- verified context before invoking these RPCs.
--
-- The new RPCs are executable only by the service_role used by the backend.
--
-- The backend must also supply p_created_by and p_received_by from req.user,
-- never from a client-controlled auth payload.
--
-- HISTORY INTEGRATION NOTE (conceptual, not implemented in this migration):
-- The existing /api/transfers/history and Deliveries page currently aggregate
-- stock_transactions history. Those callers must eventually be updated to
-- understand transfer-header grouping instead of counting rows only.
--
-- Required backend response changes for the new multi-product transfer flow:
--  1. Keep legacy single-product transfer payloads unchanged for old records.
--  2. Emit one aggregate transfer group per tracking_code for new multi-product
--     transfers, with a single top-level transfer record and a nested products[]
--     array under it.
--  3. Each nested product item keeps the original product order and quantity,
--     without duplicating the same transfer via both TRANSFER_OUT and TRANSFER_IN.
--  4. Aggregation must group by transfer_headers.id or tracking_code and exclude
--     the duplicate count of matching TRANSFER_OUT/TRANSFER_IN rows from the same
--     transfer when building the UI totals.
--  5. Do not write any new delivery_transactions rows in this migration: the
--     existing transaction history is still the source of truth for legacy data,
--     and the new history grouping should be added in the backend contract rather
--     than by modifying the transaction schema here.
--
-- This migration intentionally does not add delivery_transactions writes because
-- there is no verified requirement for backward-compatible history and doing so
-- would duplicate the single-product transfer history model that the current UI
-- already consumes.

