-- Supabase schema and RPCs for NAH inventory
-- Safe, idempotent migration script designed to preserve existing data and compatibility.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  email TEXT UNIQUE,
  full_name TEXT,
  role TEXT NOT NULL DEFAULT 'admin',
  branch TEXT,
  assigned_branch TEXT,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_login_at TIMESTAMPTZ
);

CREATE TABLE IF NOT EXISTS public.branches (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  branch_code TEXT NOT NULL UNIQUE,
  name TEXT NOT NULL UNIQUE,
  status TEXT NOT NULL DEFAULT 'active',
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  sku TEXT UNIQUE,
  barcode TEXT UNIQUE,
  product_name TEXT NOT NULL,
  category TEXT,
  expiration_date DATE,
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS public.inventory (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE RESTRICT,
  branch_id BIGINT NOT NULL REFERENCES public.branches(id) ON DELETE RESTRICT,
  branch TEXT NOT NULL DEFAULT 'Main',
  quantity INTEGER NOT NULL DEFAULT 0,
  last_updated TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT inventory_product_branch_unique UNIQUE (product_id, branch_id)
);

CREATE TABLE IF NOT EXISTS public.stock_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE RESTRICT,
  branch_id BIGINT NOT NULL REFERENCES public.branches(id) ON DELETE RESTRICT,
  barcode TEXT NOT NULL,
  branch TEXT NOT NULL DEFAULT 'Main',
  type TEXT NOT NULL CHECK (type IN ('RECEIVE', 'CONSUME')),
  quantity INTEGER NOT NULL,
  user_name TEXT NOT NULL DEFAULT 'system',
  date TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_products_barcode ON public.products(barcode);
CREATE INDEX IF NOT EXISTS idx_inventory_product_branch ON public.inventory(product_id, branch_id);
CREATE INDEX IF NOT EXISTS idx_inventory_branch ON public.inventory(branch_id);
CREATE INDEX IF NOT EXISTS idx_stock_transactions_product_branch ON public.stock_transactions(product_id, branch_id, date DESC);
CREATE INDEX IF NOT EXISTS idx_users_username ON public.users(username);
CREATE INDEX IF NOT EXISTS idx_users_email ON public.users(email);

ALTER TABLE public.branches
  ADD COLUMN IF NOT EXISTS uuid UUID,
  ADD COLUMN IF NOT EXISTS branch_code TEXT,
  ADD COLUMN IF NOT EXISTS name TEXT,
  ADD COLUMN IF NOT EXISTS status TEXT,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS updated_at TIMESTAMPTZ;

ALTER TABLE public.products
  ADD COLUMN IF NOT EXISTS uuid UUID,
  ADD COLUMN IF NOT EXISTS sku TEXT,
  ADD COLUMN IF NOT EXISTS barcode TEXT,
  ADD COLUMN IF NOT EXISTS product_name TEXT,
  ADD COLUMN IF NOT EXISTS category TEXT,
  ADD COLUMN IF NOT EXISTS expiration_date DATE,
  ADD COLUMN IF NOT EXISTS description TEXT,
  ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ;

ALTER TABLE public.inventory
  ADD COLUMN IF NOT EXISTS uuid UUID,
  ADD COLUMN IF NOT EXISTS product_id BIGINT,
  ADD COLUMN IF NOT EXISTS branch_id BIGINT,
  ADD COLUMN IF NOT EXISTS branch TEXT,
  ADD COLUMN IF NOT EXISTS quantity INTEGER,
  ADD COLUMN IF NOT EXISTS last_updated TIMESTAMPTZ;

ALTER TABLE public.stock_transactions
  ADD COLUMN IF NOT EXISTS uuid UUID,
  ADD COLUMN IF NOT EXISTS product_id BIGINT,
  ADD COLUMN IF NOT EXISTS branch_id BIGINT,
  ADD COLUMN IF NOT EXISTS barcode TEXT,
  ADD COLUMN IF NOT EXISTS branch TEXT,
  ADD COLUMN IF NOT EXISTS type TEXT,
  ADD COLUMN IF NOT EXISTS quantity INTEGER,
  ADD COLUMN IF NOT EXISTS user_name TEXT,
  ADD COLUMN IF NOT EXISTS date TIMESTAMPTZ;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname = 'inventory_product_branch_unique') THEN
    ALTER TABLE public.inventory
      ADD CONSTRAINT inventory_product_branch_unique UNIQUE (product_id, branch_id);
  END IF;
END $$;

-- Foreign keys intentionally use ON DELETE RESTRICT so historical inventory
-- and transaction rows cannot be silently removed when a product or branch is deleted.

CREATE OR REPLACE FUNCTION public.(p_barcode TEXT, p_branch_code TEXT, p_qty BIGINT, p_note TEXT)
RETURNS TABLE(success BOOLEAN, message TEXT, quantity INTEGER)
LANGUAGE plpgsql
AS $$
DECLARE
  v_product_id BIGINT;
  v_branch_id BIGINT;
  v_branch_name TEXT;
  v_new_qty INTEGER;
BEGIN
  SELECT id INTO v_product_id FROM public.products WHERE barcode = p_barcode LIMIT 1;
  IF v_product_id IS NULL THEN
    RETURN QUERY SELECT false, 'product_not_found', 0;
    RETURN;
  END IF;

  SELECT id, name INTO v_branch_id, v_branch_name FROM public.branches WHERE branch_code = p_branch_code OR name = p_branch_code LIMIT 1;
  IF v_branch_id IS NULL THEN
    RETURN QUERY SELECT false, 'branch_not_found', 0;
    RETURN;
  END IF;

  INSERT INTO public.inventory(product_id, branch_id, branch, quantity, last_updated)
  VALUES (v_product_id, v_branch_id, v_branch_name, p_qty, NOW())
  ON CONFLICT (product_id, branch_id)
  DO UPDATE SET quantity = public.inventory.quantity + EXCLUDED.quantity,
                branch = EXCLUDED.branch,
                last_updated = NOW();

  INSERT INTO public.stock_transactions(product_id, branch_id, barcode, branch, type, quantity, user_name, date)
  VALUES (v_product_id, v_branch_id, p_barcode, v_branch_name, 'RECEIVE', p_qty::INTEGER, COALESCE(p_note, 'system'), NOW());

  SELECT quantity INTO v_new_qty FROM public.inventory WHERE product_id = v_product_id AND branch_id = v_branch_id;
  RETURN QUERY SELECT true, 'received', v_new_qty;
END;
$$;

CREATE OR REPLACE FUNCTION public.consume_stock(p_barcode TEXT, p_branch_code TEXT, p_qty BIGINT, p_note TEXT)
RETURNS TABLE(success BOOLEAN, message TEXT, quantity INTEGER)
LANGUAGE plpgsql
AS $$
DECLARE
  v_product_id BIGINT;
  v_branch_id BIGINT;
  v_branch_name TEXT;
  v_cur_qty INTEGER;
BEGIN
  SELECT id INTO v_product_id FROM public.products WHERE barcode = p_barcode LIMIT 1;
  IF v_product_id IS NULL THEN
    RETURN QUERY SELECT false, 'product_not_found', 0;
    RETURN;
  END IF;

  SELECT id, name INTO v_branch_id, v_branch_name FROM public.branches WHERE branch_code = p_branch_code OR name = p_branch_code LIMIT 1;
  IF v_branch_id IS NULL THEN
    RETURN QUERY SELECT false, 'branch_not_found', 0;
    RETURN;
  END IF;

  SELECT quantity INTO v_cur_qty
  FROM public.inventory
  WHERE product_id = v_product_id AND branch_id = v_branch_id
  FOR UPDATE;

  IF v_cur_qty IS NULL THEN
    RETURN QUERY SELECT false, 'inventory_not_found', 0;
    RETURN;
  END IF;

  IF v_cur_qty < p_qty::INTEGER THEN
    RETURN QUERY SELECT false, 'insufficient_stock', v_cur_qty;
    RETURN;
  END IF;

  UPDATE public.inventory
  SET quantity = quantity - p_qty::INTEGER,
      last_updated = NOW()
  WHERE product_id = v_product_id AND branch_id = v_branch_id;

  INSERT INTO public.stock_transactions(product_id, branch_id, barcode, branch, type, quantity, user_name, date)
  VALUES (v_product_id, v_branch_id, p_barcode, v_branch_name, 'CONSUME', p_qty::INTEGER, COALESCE(p_note, 'system'), NOW());

  SELECT quantity INTO v_cur_qty FROM public.inventory WHERE product_id = v_product_id AND branch_id = v_branch_id;
  RETURN QUERY SELECT true, 'consumed', v_cur_qty;
END;
$$;
