-- Delivery migration for source-to-destination branch transfers.
-- This version is CORRECTED to match the actual live Supabase schema.
-- 
-- Schema notes:
-- - branches.id is UUID (not BIGINT)
-- - branches.branch_name is the actual column (not name)
-- - inventory uses product_uuid (not product_id BIGINT)
-- - stock_transactions uses product_uuid (not product_id BIGINT)
-- - delivery_transactions table must be created

-- Create delivery_transactions table (required)
CREATE TABLE IF NOT EXISTS public.delivery_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  uuid UUID NOT NULL UNIQUE DEFAULT gen_random_uuid(),
  source_branch_id UUID NOT NULL,
  destination_branch_id UUID NOT NULL,
  product_uuid UUID NOT NULL,
  barcode TEXT NOT NULL,
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  user_name TEXT NOT NULL DEFAULT 'system',
  status TEXT NOT NULL DEFAULT 'PENDING' CHECK (status IN ('PENDING', 'DISPATCHED', 'RECEIVED', 'CANCELLED')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT delivery_source_dest_not_same CHECK (source_branch_id <> destination_branch_id)
);

CREATE INDEX IF NOT EXISTS idx_delivery_transactions_source ON public.delivery_transactions(source_branch_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_delivery_transactions_destination ON public.delivery_transactions(destination_branch_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_delivery_transactions_product ON public.delivery_transactions(product_uuid, created_at DESC);

-- Create or replace the deliver_stock RPC with corrected schema references
CREATE OR REPLACE FUNCTION public.deliver_stock(
  p_from_branch_id UUID,
  p_to_branch_id UUID,
  p_barcode TEXT,
  p_qty INTEGER,
  p_user TEXT
)
RETURNS TABLE(success BOOLEAN, message TEXT, quantity INTEGER)
LANGUAGE plpgsql
AS $$
DECLARE
  v_product_uuid UUID;
  v_from_branch_name TEXT;
  v_to_branch_name TEXT;
  v_source_qty INTEGER;
  v_destination_qty INTEGER;
BEGIN
  -- Validate input parameters
  IF p_from_branch_id IS NULL OR p_to_branch_id IS NULL THEN
    RETURN QUERY SELECT false, 'source_and_destination_required', 0;
    RETURN;
  END IF;

  IF p_from_branch_id = p_to_branch_id THEN
    RETURN QUERY SELECT false, 'source_and_destination_must_differ', 0;
    RETURN;
  END IF;

  IF p_barcode IS NULL OR trim(p_barcode) = '' THEN
    RETURN QUERY SELECT false, 'product_barcode_required', 0;
    RETURN;
  END IF;

  IF p_qty IS NULL OR p_qty <= 0 THEN
    RETURN QUERY SELECT false, 'quantity_must_be_positive', 0;
    RETURN;
  END IF;

  -- Validate product exists by barcode and get its UUID
  SELECT uuid INTO v_product_uuid
  FROM public.products
  WHERE barcode = trim(p_barcode)
  LIMIT 1;

  IF v_product_uuid IS NULL THEN
    RETURN QUERY SELECT false, 'product_not_found', 0;
    RETURN;
  END IF;

  -- Validate source branch exists
  IF NOT EXISTS (SELECT 1 FROM public.branches WHERE id = p_from_branch_id) THEN
    RETURN QUERY SELECT false, 'source_branch_not_found', 0;
    RETURN;
  END IF;

  -- Validate destination branch exists
  IF NOT EXISTS (SELECT 1 FROM public.branches WHERE id = p_to_branch_id) THEN
    RETURN QUERY SELECT false, 'destination_branch_not_found', 0;
    RETURN;
  END IF;

  -- Get source inventory quantity with row lock (FOR UPDATE)
  SELECT quantity INTO v_source_qty
  FROM public.inventory
  WHERE product_uuid = v_product_uuid AND branch_id = p_from_branch_id
  FOR UPDATE;

  IF v_source_qty IS NULL THEN
    RETURN QUERY SELECT false, 'inventory_not_found', 0;
    RETURN;
  END IF;

  -- Check sufficient stock
  IF v_source_qty < p_qty THEN
    RETURN QUERY SELECT false, 'insufficient_stock', v_source_qty;
    RETURN;
  END IF;

  -- Get branch names for transaction records
  SELECT branch_name INTO v_from_branch_name FROM public.branches WHERE id = p_from_branch_id;
  SELECT branch_name INTO v_to_branch_name FROM public.branches WHERE id = p_to_branch_id;

  -- DEDUCT from source branch inventory
  UPDATE public.inventory
  SET quantity = quantity - p_qty,
      last_updated = NOW()
  WHERE product_uuid = v_product_uuid AND branch_id = p_from_branch_id;

  -- ADD to destination branch inventory (insert if not exists, update if exists)
  INSERT INTO public.inventory(product_uuid, branch_id, branch, quantity, last_updated)
  VALUES (v_product_uuid, p_to_branch_id, v_to_branch_name, p_qty, NOW())
  ON CONFLICT (product_uuid, branch_id)
  DO UPDATE SET quantity = public.inventory.quantity + EXCLUDED.quantity,
                last_updated = NOW();

  -- Record stock transaction for source (CONSUME)
  INSERT INTO public.stock_transactions(product_uuid, branch_id, barcode, branch, type, quantity, user_name, date)
  VALUES (
    v_product_uuid,
    p_from_branch_id,
    trim(p_barcode),
    v_from_branch_name,
    'CONSUME',
    p_qty,
    COALESCE(p_user, 'system'),
    NOW()
  );

  -- Record stock transaction for destination (RECEIVE)
  INSERT INTO public.stock_transactions(product_uuid, branch_id, barcode, branch, type, quantity, user_name, date)
  VALUES (
    v_product_uuid,
    p_to_branch_id,
    trim(p_barcode),
    v_to_branch_name,
    'RECEIVE',
    p_qty,
    COALESCE(p_user, 'system'),
    NOW()
  );

  -- Record delivery transaction
  INSERT INTO public.delivery_transactions(
    source_branch_id,
    destination_branch_id,
    product_uuid,
    barcode,
    quantity,
    user_name,
    status,
    created_at,
    updated_at
  )
  VALUES (
    p_from_branch_id,
    p_to_branch_id,
    v_product_uuid,
    trim(p_barcode),
    p_qty,
    COALESCE(p_user, 'system'),
    'PENDING',
    NOW(),
    NOW()
  );

  -- Get final destination quantity
  SELECT quantity INTO v_destination_qty
  FROM public.inventory
  WHERE product_uuid = v_product_uuid AND branch_id = p_to_branch_id;

  RETURN QUERY SELECT true, 'delivery_recorded', COALESCE(v_destination_qty, 0);
END;
$$;
